services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - mongodb_data_container:/data/db
  # backend:
  #   depends_on:
  #     - mongo
  #   build: ./backend
  #   restart: always
  #   ports:
  #     - ${USER_PORT}:${USER_PORT}
  #   environment:
  #     - USER_PORT=${USER_PORT}
  #     - JWT_KEY=${JWT_KEY}
  #     - MONGO_URL=mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:${MONGO_PORT}
  #   stdin_open: true
  #   tty: true
volumes:
  mongodb_data_container:
