services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - mongodb_data_container:/data/db
  osrm:
    build: ./osrm
    restart: always
    ports:
      - ${OSRM_EXTERNAL_PORT}:${OSRM_INTERNAL_PORT}
    command: ${OSRM_COMMAND}

  backend:
    depends_on:
      - mongo
    build: ./backend
    restart: always
    ports:
      - ${USER_PORT}:${USER_PORT}
    environment:
      - USER_PORT=${USER_PORT}
      - JWT_KEY=${JWT_KEY}
      - MONGO_URL=mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:${MONGO_PORT}
      - OSRM_URL=http://@osrm:${OSRM_INTERNAL_PORT}
      - GEOWORD_URL=http://@geoword:${GEOWORD_PORT}
    stdin_open: true
    tty: true
  auth:
    depends_on:
      - backend
    build: ./auth
    restart: always
    ports:
      - ${AUTH_PORT}:${AUTH_PORT}
    environment:
      - PORT=${AUTH_PORT}
      - JWT_SECRET=${JWT_KEY}
      - ROUTE_ADDRESS=http://@backend:${USER_PORT}
    stdin_open: true
    tty: true

volumes:
  mongodb_data_container:
